---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install tree command 
      yum:
        name: tree
        state: present

    - name:   Install httpd
      yum:
        name: httpd
        state: present

    - name: Enable httpd service
      service:
        name: httpd
        enabled: yes

