---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Remove tree command
      ansible.builtin.yum:
        name: tree
        state: absente
    - name: Install tree command
      dnf: 
       name: tree]
       state: present
